/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cryptionsoftware;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author arnavprabhale
 */
public class Frame extends javax.swing.JFrame
{

    /**
     * Creates new form Frame
     */
    String path = "/Users/arnavprabhale/Downloads";
    String name = "";
    String extension = "";
    
    
    public Frame()
    {
        initComponents();
        
        ImageIcon imageIcon = new ImageIcon(new ImageIcon("/Users/arnavprabhale/NetBeansProjects/cryptionSoftware/src/main/java/img/folders icon.jpeg").getImage().getScaledInstance(lblimage.getWidth()-5, lblimage.getHeight()-5, Image.SCALE_SMOOTH));
        lblimage.setIcon(imageIcon);
        txtpass.setVisible(false);
        pfpass.setVisible(false);
        btnsubmit.setVisible(false);
        
        
        //lblimage.setIcon(new ImageIcon("/Users/arnavprabhale/NetBeansProjects/cryptionSoftware/src/main/java/img/folders icon.jpeg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        filePanel = new javax.swing.JPanel();
        lblimage = new javax.swing.JLabel();
        btnload = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btndecrpt = new javax.swing.JButton();
        btnencrpt = new javax.swing.JButton();
        lblfilename = new javax.swing.JLabel();
        txtpass = new javax.swing.JLabel();
        pfpass = new javax.swing.JPasswordField();
        btnsubmit = new javax.swing.JButton();
        lblmessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        filePanel.setBackground(new java.awt.Color(255, 255, 255));

        lblimage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblimage.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                lblimageMouseMoved(evt);
            }
        });
        lblimage.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblimageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lblimageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lblimageMouseExited(evt);
            }
        });

        btnload.setBackground(new java.awt.Color(100, 174, 248));
        btnload.setFont(new java.awt.Font("Telugu MN", 1, 24)); // NOI18N
        btnload.setForeground(new java.awt.Color(255, 255, 255));
        btnload.setText("UPLOAD FILE HERE ");
        btnload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnload.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnloadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout filePanelLayout = new javax.swing.GroupLayout(filePanel);
        filePanel.setLayout(filePanelLayout);
        filePanelLayout.setHorizontalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filePanelLayout.createSequentialGroup()
                .addComponent(btnload, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        filePanelLayout.setVerticalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnload, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(lblimage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Easily Encrypt / Decrypt Files(pdf, jpg, jpeg, pptx, doc, etc..) ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(filePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(203, 3, 85));

        btndecrpt.setBackground(new java.awt.Color(76, 130, 225));
        btndecrpt.setFont(new java.awt.Font("Telugu MN", 1, 24)); // NOI18N
        btndecrpt.setForeground(new java.awt.Color(255, 255, 255));
        btndecrpt.setText("Decrypt");
        btndecrpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndecrpt.setEnabled(false);
        btndecrpt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btndecrptActionPerformed(evt);
            }
        });

        btnencrpt.setBackground(new java.awt.Color(76, 130, 225));
        btnencrpt.setFont(new java.awt.Font("Telugu MN", 1, 24)); // NOI18N
        btnencrpt.setForeground(new java.awt.Color(255, 255, 255));
        btnencrpt.setText("Encrypt");
        btnencrpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnencrpt.setEnabled(false);
        btnencrpt.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnencrptMouseClicked(evt);
            }
        });
        btnencrpt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnencrptActionPerformed(evt);
            }
        });

        lblfilename.setFont(new java.awt.Font("Menlo", 1, 22)); // NOI18N
        lblfilename.setForeground(new java.awt.Color(255, 255, 255));
        lblfilename.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtpass.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        txtpass.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtpass.setText("PASSWORD");

        pfpass.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        btnsubmit.setBackground(new java.awt.Color(51, 204, 0));
        btnsubmit.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnencrpt, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btndecrpt, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pfpass, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(175, 175, 175))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblfilename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblfilename, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnencrpt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndecrpt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfpass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsubmit))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        lblmessage.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        lblmessage.setForeground(new java.awt.Color(51, 204, 0));
        lblmessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(lblmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblimageMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblimageMouseMoved
    {//GEN-HEADEREND:event_lblimageMouseMoved
        // TODO add your handling code here:
        ImageIcon imageIcon = new ImageIcon(new ImageIcon("/Users/arnavprabhale/NetBeansProjects/cryptionSoftware/src/main/java/img/folders icon.jpeg").getImage().getScaledInstance(lblimage.getWidth(), lblimage.getHeight(), Image.SCALE_SMOOTH));
        lblimage.setIcon(imageIcon);
        
    }//GEN-LAST:event_lblimageMouseMoved

    private void lblimageMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblimageMouseEntered
    {//GEN-HEADEREND:event_lblimageMouseEntered
        // TODO add your handling code here:
        ImageIcon imageIcon = new ImageIcon(new ImageIcon("/Users/arnavprabhale/NetBeansProjects/cryptionSoftware/src/main/java/img/folders icon.jpeg").getImage().getScaledInstance(lblimage.getWidth(), lblimage.getHeight(), Image.SCALE_SMOOTH));
        lblimage.setIcon(imageIcon);
    }//GEN-LAST:event_lblimageMouseEntered

    private void lblimageMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblimageMouseExited
    {//GEN-HEADEREND:event_lblimageMouseExited
        // TODO add your handling code here:
        ImageIcon imageIcon = new ImageIcon(new ImageIcon("/Users/arnavprabhale/NetBeansProjects/cryptionSoftware/src/main/java/img/folders icon.jpeg").getImage().getScaledInstance(lblimage.getWidth()-5, lblimage.getHeight()-5, Image.SCALE_SMOOTH));
        lblimage.setIcon(imageIcon);
    }//GEN-LAST:event_lblimageMouseExited

    private void btnloadMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnloadMouseClicked
    {//GEN-HEADEREND:event_btnloadMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser(path);
        
        int response = fileChooser.showOpenDialog(mainPanel);
        
        if(response == JFileChooser.APPROVE_OPTION)
        {
            path = fileChooser.getSelectedFile().getAbsolutePath();
            name = fileChooser.getSelectedFile().getName();
            extension = FilenameUtils.getExtension(path);
            System.out.println(extension);
            lblfilename.setText(name);
            lblfilename.setBackground(Color.LIGHT_GRAY);
            String scopio = "sopiro";
//            lblfilename.setText("");
//            lblmessage.setText("");
            if(extension.equals(scopio))
            {
//                btnencrpt.setEnabled(false);
//                btndecrpt.setEnabled(true);
                txtpass.setVisible(true);
                pfpass.setVisible(true);
                btnsubmit.setVisible(true);
                
                
            }
            else
            {
                btnencrpt.setEnabled(true);
                btndecrpt.setEnabled(false);
                txtpass.setVisible(false);
                pfpass.setVisible(false);
                btnsubmit.setVisible(false);               
            }
            
            
            
            
        }
        
    }//GEN-LAST:event_btnloadMouseClicked

    private void btndecrptActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btndecrptActionPerformed
    {//GEN-HEADEREND:event_btndecrptActionPerformed
        // TODO add your handling code here:
        Decryptor de = Decryptor.getDecrypter(true);

        File src = new File(path);
        String newpath = path.substring(0, path.length() - (name.length() + 1));
        System.out.println(newpath + "       " + name.length());
       
        File rec = new File(newpath);
        int check = de.decrypt(src, rec);
 
        if (src.delete()) 
        {
            System.out.println("File deleted successfully");
        }
        else 
        {
            System.out.println("Failed to delete the file");
        }
        
        if(check == 1)
        {
            String messageString = "<html>Decrypted SuccessFully<br/>Your Files are Safe Now!!</html>";
            lblmessage.setText(messageString);
            btnencrpt.setEnabled(false);
            btndecrpt.setEnabled(false);
            
        }
        else
        {
            String messageString = "<html>Oops!! Error Occured <br/>Try Again..</html>";
            lblmessage.setText(messageString);
            btnencrpt.setEnabled(false);
            btndecrpt.setEnabled(false);
        }
    }//GEN-LAST:event_btndecrptActionPerformed

    private void btnencrptMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnencrptMouseClicked
    {//GEN-HEADEREND:event_btnencrptMouseClicked
        // TODO add your handling code here:
        System.out.println("Encrypt clicked");
        Encryptor en = Encryptor.getEncrypter(true);
		
        String newpath = path.substring(0, path.length() - (name.length() + 1));
        System.out.println(newpath + "       " + name.length());
        
        File src = new File(path);
        File rec = new File(newpath);
        System.out.println(path);
        int check = en.encrypt(src, rec);
        System.out.println("Done Encryption");
        
        if (src.delete()) 
        {
            System.out.println("File deleted successfully");
        }
        else 
        {
            System.out.println("Failed to delete the file");
        }
        
        if(check == 1)
        {
            String messageString = "<html>Encrypted SuccessFully<br/>Your Files are Safe Now!!!</html>";
            lblmessage.setText(messageString);
            btnencrpt.setEnabled(false);
            btndecrpt.setEnabled(false);
        }
        else
        {
            String messageString = "<html>Oops!! Error Occured<br/>Try Again..</html>";
            lblmessage.setText(messageString);
            btnencrpt.setEnabled(false);
            btndecrpt.setEnabled(false);
        }
            
        
        
    }//GEN-LAST:event_btnencrptMouseClicked

    private void lblimageMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblimageMouseClicked
    {//GEN-HEADEREND:event_lblimageMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("/Users/arnavprabhale/Downloads");
        
        int response = fileChooser.showOpenDialog(mainPanel);
        
        if(response == JFileChooser.APPROVE_OPTION)
        {
            path = fileChooser.getSelectedFile().getAbsolutePath();
           // System.out.println(path);
            String name = fileChooser.getSelectedFile().getName();
            System.out.println(name);
            lblfilename.setText(name);
            lblfilename.setBackground(Color.LIGHT_GRAY);
            btnencrpt.setEnabled(true);
            btndecrpt.setEnabled(true);
            
        }
    }//GEN-LAST:event_lblimageMouseClicked

    private void btnencrptActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnencrptActionPerformed
    {//GEN-HEADEREND:event_btnencrptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnencrptActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnsubmitActionPerformed
    {//GEN-HEADEREND:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        String check = new String(pfpass.getPassword());
        System.out.println(check);

        if(check.equals("pass123"))
        {
            btnencrpt.setEnabled(false);
            btndecrpt.setEnabled(true);

            txtpass.setText("Verified User");
            pfpass.setVisible(false);
            btnsubmit.setVisible(false);
        }
        else
        {
            pfpass.setText("");
            btnsubmit.setText("RETRY");
        }
        
        
    }//GEN-LAST:event_btnsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndecrpt;
    private javax.swing.JButton btnencrpt;
    private javax.swing.JButton btnload;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JPanel filePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblfilename;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel lblmessage;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField pfpass;
    private javax.swing.JLabel txtpass;
    // End of variables declaration//GEN-END:variables
}
